### ISSUE TITLE
日志出现错误，Error: invalid query, params or body

### ISSUE THREAD

**Issue by hailiang-wang** [chatopera/chatopera.fmc#1]
```
  CLICK_YES_MSG: [ '感谢您的支持！', '祝您有美好的一天！', '期待再次为您服务。' ],
     CLICK_NO_MSG:
      [ '请优化检索条件再试一下。',
        '非常抱歉没有帮助您解决问题，机器人客服的技能还在提升！',
        '非常抱歉，稍后为您转人工处理，请耐心等待或发送邮件到 some@email.com' ] } } +2s
  fmc:service:chat user query undefined on +3ms
  fmc:service:chat  user query msg undefined +1ms
  --> POST /webhook 200 11ms 0b
Error: invalid query, params or body.
    at ChatoperaService.conversationQuery /chatopera.fmc/fmc/app/services/chatopera.service.js:36:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by hailiang-wang** [comment]
从 FB 接受到消息如下：

```
 fmc:route:webhook webhook body [
  {
    "id": "xxx",
    "time": 1606368591919,
    "messaging": [
      {
        "sender": {
          "id": "xxx"
        },
        "recipient": {
          "id": "xxx"
        },
        "timestamp": xx,
        "delivery": {
          "mids": [
            "-br9eouk8EOaon1nL8n2sqHNrecKmTAxf6l_zHsjmbMCw"
          ],
          "watermark": 1606368591559
        }
      }
    ]
  }
]
```

以上不清楚代表什么含义，应该忽略该消息的处理。
